src/main/java/com/algaworks/financeiro/model/Lancamento.java
package com.algaworks.financeiro.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

import com.algaworks.financeiro.validation.DecimalPositivo;

@Entity
@Table(name = "lancamento")
public class Lancamento implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long id;
	private Pessoa pessoa;
	private String descricao;
	private BigDecimal valor;
	private TipoLancamento tipo;
	private Date dataVencimento;
	private Date dataPagamento;

	@Id
	@GeneratedValue
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@NotNull
	@ManyToOne(optional = false)
	@JoinColumn(name = "pessoa_id")
	public Pessoa getPessoa() {
		return pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	@NotEmpty
	@Size(max = 80)
	@Column(length = 80, nullable = false)
	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@DecimalPositivo
	@Column(precision = 10, scale = 2, nullable = false)
	public BigDecimal getValor() {
		return valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(nullable = false)
	public TipoLancamento getTipo() {
		return tipo;
	}

	public void setTipo(TipoLancamento tipo) {
		this.tipo = tipo;
	}

	@NotNull
	@Temporal(TemporalType.DATE)
	@Column(name = "data_vencimento", nullable = false)
	public Date getDataVencimento() {
		return dataVencimento;
	}

	public void setDataVencimento(Date dataVencimento) {
		this.dataVencimento = dataVencimento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_pagamento", nullable = true)
	public Date getDataPagamento() {
		return dataPagamento;
	}

	public void setDataPagamento(Date dataPagamento) {
		this.dataPagamento = dataPagamento;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Lancamento other = (Lancamento) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}

src/main/java/com/algaworks/financeiro/model/Pessoa.java
package com.algaworks.financeiro.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

@Entity
@Table(name = "pessoa")
public class Pessoa implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long id;
	private String nome;

	@Id
	@GeneratedValue
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@NotEmpty
	@Size(max = 60)
	@Column(length = 60, nullable = false)
	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Pessoa other = (Pessoa) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}

src/main/java/com/algaworks/financeiro/model/TipoLancamento.java
package com.algaworks.financeiro.model;

public enum TipoLancamento {

	RECEITA("Receita"), 
	DESPESA("Despesa");

	private String descricao;
	
	TipoLancamento(String descricao) {
		this.descricao = descricao;
	}

	public String getDescricao() {
		return descricao;
	}

}

src/main/java/com/algaworks/financeiro/controller/CadastroLancamentoBean.java
package com.algaworks.financeiro.controller;

import java.io.Serializable;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.event.AjaxBehaviorEvent;
import javax.inject.Inject;
import javax.inject.Named;

import com.algaworks.financeiro.model.Lancamento;
import com.algaworks.financeiro.model.Pessoa;
import com.algaworks.financeiro.model.TipoLancamento;
import com.algaworks.financeiro.repository.Lancamentos;
import com.algaworks.financeiro.repository.Pessoas;
import com.algaworks.financeiro.service.CadastroLancamentos;
import com.algaworks.financeiro.service.NegocioException;

@Named
@javax.faces.view.ViewScoped
public class CadastroLancamentoBean implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@Inject
	private CadastroLancamentos cadastro;
	
	@Inject
	private Pessoas pessoas;
	
	@Inject
	private Lancamentos lancamentos;
	
	private Lancamento lancamento;
	private List<Pessoa> todasPessoas;

	public void prepararCadastro() {
		this.todasPessoas = this.pessoas.todas();
		
		if (this.lancamento == null) {
			this.lancamento = new Lancamento();
		}
	}
	
	public List<String> pesquisarDescricoes(String descricao) {
		return this.lancamentos.descricoesQueContem(descricao);
	}
	
	public void dataVencimentoAlterada(AjaxBehaviorEvent event) {
		if (this.lancamento.getDataPagamento() == null) {
			this.lancamento.setDataPagamento(this.lancamento.getDataVencimento());
		}
	}
	
	public void salvar() {
		FacesContext context = FacesContext.getCurrentInstance();
		
		try {
			this.cadastro.salvar(this.lancamento);
			
			this.lancamento = new Lancamento();
			context.addMessage(null, new FacesMessage("Lançamento salvo com sucesso!"));
		} catch (NegocioException e) {
			
			FacesMessage mensagem = new FacesMessage(e.getMessage());
			mensagem.setSeverity(FacesMessage.SEVERITY_ERROR);
			context.addMessage(null, mensagem);
		}
	}
	
	public List<Pessoa> getTodasPessoas() {
		return this.todasPessoas;
	}
	
	public TipoLancamento[] getTiposLancamentos() {
		return TipoLancamento.values();
	}
	
	public Lancamento getLancamento() {
		return lancamento;
	}

	public void setLancamento(Lancamento lancamento) {
		this.lancamento = lancamento;
	}
	
}

src/main/java/com/algaworks/financeiro/controller/ConsultaLancamentosBean.java
package com.algaworks.financeiro.controller;

import java.io.Serializable;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.algaworks.financeiro.model.Lancamento;
import com.algaworks.financeiro.repository.Lancamentos;
import com.algaworks.financeiro.service.CadastroLancamentos;
import com.algaworks.financeiro.service.NegocioException;

@Named
@ViewScoped
public class ConsultaLancamentosBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	private Lancamentos lancamentosRepository;
	
	@Inject
	private CadastroLancamentos cadastro;
	
	private List<Lancamento> lancamentos;
	
	private Lancamento lancamentoSelecionado;

	public void excluir() {
		FacesContext context = FacesContext.getCurrentInstance();
		
		try {
			this.cadastro.excluir(this.lancamentoSelecionado);
			this.consultar();
			
			context.addMessage(null, new FacesMessage("Lançamento excluído com sucesso!"));
		} catch (NegocioException e) {
			
			FacesMessage mensagem = new FacesMessage(e.getMessage());
			mensagem.setSeverity(FacesMessage.SEVERITY_ERROR);
			context.addMessage(null, mensagem);
		}
	}
	
	public void consultar() {
		this.lancamentos = lancamentosRepository.todos(); 
	}
	
	public List<Lancamento> getLancamentos() {
		return lancamentos;
	}

	public Lancamento getLancamentoSelecionado() {
		return lancamentoSelecionado;
	}

	public void setLancamentoSelecionado(Lancamento lancamentoSelecionado) {
		this.lancamentoSelecionado = lancamentoSelecionado;
	}

}

src/main/java/com/algaworks/financeiro/controller/LoginBean.java
package com.algaworks.financeiro.controller;

import java.util.Date;

import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

@Named
@RequestScoped
public class LoginBean {

	@Inject
	private Usuario usuario;
	
	private String nomeUsuario;
	private String senha;

	public String login() {
		FacesContext context = FacesContext.getCurrentInstance();
		
		if ("admin".equals(this.nomeUsuario) && "123".equals(this.senha)) {
			this.usuario.setNome(this.nomeUsuario);
			this.usuario.setDataLogin(new Date());
			
			return "/ConsultaLancamentos?faces-redirect=true";
		} else {
			FacesMessage mensagem = new FacesMessage("Usuário/senha inválidos!");
			mensagem.setSeverity(FacesMessage.SEVERITY_ERROR);
			context.addMessage(null, mensagem);
		}
		
		return null;
	}
	
	public String logout() {
		FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
		return "/Login?faces-redirect=true";
	}
	
	public String getNomeUsuario() {
		return nomeUsuario;
	}

	public void setNomeUsuario(String nomeUsuario) {
		this.nomeUsuario = nomeUsuario;
	}

	public String getSenha() {
		return senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

}

src/main/webapp/CadastroLancamento.xhtml
<!DOCTYPE html>
<ui:composition template="/WEB-INF/template/Layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:o="http://omnifaces.org/ui">

	<f:metadata>
		<o:viewParam name="id" value="#{cadastroLancamentoBean.lancamento}" />
		<f:viewAction action="#{cadastroLancamentoBean.prepararCadastro}" />
	</f:metadata>

	<ui:define name="titulo">Cadastro de lançamento</ui:define>

	<ui:define name="corpo">
		<h1>Cadastro de lançamento</h1>

		<h:form id="frm">
			<p:messages showDetail="false" showSummary="true" autoUpdate="true" />
		
			<p:panelGrid columns="2" id="grid">
				<p:outputLabel value="Tipo" for="tipo" />
				<p:selectOneButton id="tipo" 
						value="#{cadastroLancamentoBean.lancamento.tipo}">
					<f:selectItems value="#{cadastroLancamentoBean.tiposLancamentos}"
						var="tipoLancamento" itemValue="#{tipoLancamento}" 
						itemLabel="#{tipoLancamento.descricao}" />
				</p:selectOneButton>

				<p:outputLabel value="Pessoa" for="pessoa" />
				<p:selectOneMenu value="#{cadastroLancamentoBean.lancamento.pessoa}"
						id="pessoa" filter="true" filterMatchMode="contains">
					<f:selectItem itemLabel="Selecione" noSelectionOption="true" />
					<f:selectItems value="#{cadastroLancamentoBean.todasPessoas}"
						var="pessoa" itemValue="#{pessoa}" itemLabel="#{pessoa.nome}" />
				</p:selectOneMenu>

				<p:outputLabel value="Descrição" for="descricao" />
				<p:autoComplete id="descricao" size="60" 
					value="#{cadastroLancamentoBean.lancamento.descricao}"
					completeMethod="#{cadastroLancamentoBean.pesquisarDescricoes}" />

				<p:outputLabel value="Valor" for="valor" />
				<p:inputText id="valor" size="12" 
						value="#{cadastroLancamentoBean.lancamento.valor}">
					<f:convertNumber locale="pt_BR" maxFractionDigits="2" minFractionDigits="2" />
				</p:inputText>

				<p:outputLabel value="Data de vencimento" for="dataVencimento" />
				<p:calendar id="dataVencimento" size="12" pattern="dd/MM/yyyy"
						value="#{cadastroLancamentoBean.lancamento.dataVencimento}">
					<p:ajax event="dateSelect" update="@this dataPagamento" process="@this dataPagamento" 
						listener="#{cadastroLancamentoBean.dataVencimentoAlterada}" />
					<p:ajax event="change" update="@this dataPagamento" process="@this dataPagamento" 
						listener="#{cadastroLancamentoBean.dataVencimentoAlterada}" />
				</p:calendar>
				
				<p:outputLabel value="Data de pagamento" for="dataPagamento" />
				<p:calendar size="12" id="dataPagamento" pattern="dd/MM/yyyy" 
					value="#{cadastroLancamentoBean.lancamento.dataPagamento}" />

				<h:outputLabel />
				<p:commandButton value="Salvar" action="#{cadastroLancamentoBean.salvar}"
					icon="ui-icon-disk" update="@form" />
			</p:panelGrid>
		</h:form>
	</ui:define>

</ui:composition>

src/main/webapp/ConsultaLancamentos.xhtml
<!DOCTYPE html>
<ui:composition template="/WEB-INF/template/Layout.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<f:metadata>
		<f:viewAction action="#{consultaLancamentosBean.consultar}" />
	</f:metadata>

    <ui:define name="titulo">Consulta de lançamentos</ui:define>
    
    <ui:define name="corpo">
		
		<h1>Consulta de lançamentos</h1>
	
		<h:form id="frm">
			<p:messages showDetail="false" showSummary="true" autoUpdate="true" />
		
			<p:dataTable value="#{consultaLancamentosBean.lancamentos}" var="lancamento"
					border="1" cellspacing="0" cellpadding="2"
					paginator="true" rows="5" paginatorPosition="bottom">
				<p:column headerText="Pessoa" sortBy="#{lancamento.pessoa.nome}">
					<h:outputText value="#{lancamento.pessoa.nome}" />
				</p:column>
				<p:column headerText="Descrição" sortBy="#{lancamento.descricao}">
					<h:outputText value="#{lancamento.descricao}" />
				</p:column>
				<p:column headerText="Tipo" width="80">
					<h:outputText value="#{lancamento.tipo.descricao}" />
				</p:column>
				<p:column headerText="Valor" style="text-align: right" sortBy="#{lancamento.valor}"
						width="100">
					<h:outputText value="#{lancamento.valor}">
						<f:convertNumber type="currency" locale="pt_BR" />
					</h:outputText>
				</p:column>
				<p:column headerText="Vencimento" style="text-align: center" sortBy="#{lancamento.dataVencimento}"
						width="100">
					<h:outputText value="#{lancamento.dataVencimento}">
						<f:convertDateTime pattern="dd/MM/yyyy" timeZone="America/Sao_Paulo" />
					</h:outputText>
				</p:column>
				<p:column headerText="Pagamento" style="text-align: center" sortBy="#{lancamento.dataPagamento}"
						width="100">
					<h:outputText value="#{lancamento.dataPagamento}">
						<f:convertDateTime pattern="dd/MM/yyyy" timeZone="America/Sao_Paulo" />
					</h:outputText>
				</p:column>
				<p:column width="70" style="text-align: center">
					<p:button icon="ui-icon-pencil" title="Editar" outcome="/CadastroLancamento">
						<f:param name="id" value="#{lancamento.id}" />
					</p:button>
					<p:commandButton icon="ui-icon-trash" title="Excluir" process="@this" update="@form"
							action="#{consultaLancamentosBean.excluir}">
	    				<f:setPropertyActionListener value="#{lancamento}" 
	    					target="#{consultaLancamentosBean.lancamentoSelecionado}" />
	    			</p:commandButton>
				</p:column>
			</p:dataTable>
		</h:form>
	</ui:define>

</ui:composition>

src/main/webapp/Login.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>Login</title>
	<h:outputStylesheet library="algaworks" name="estilo.css" />
</h:head>

<h:body>

	<div id="login-dialog">
		<h1>Login</h1>
		
		<h:form id="frm">
			<p:messages autoUpdate="true" />
	
			<h:panelGrid columns="2" styleClass="grid-login">
				<p:outputLabel value="Usuário" for="usuario" />
				<p:inputText id="usuario" size="20" value="#{loginBean.nomeUsuario}" />
				
				<p:outputLabel value="Senha" for="senha" />
				<p:password id="senha" size="20" value="#{loginBean.senha}" />
				
				<p:outputLabel />
				<p:commandButton value="Acessar" action="#{loginBean.login}" />
			</h:panelGrid>
		</h:form>
	</div>
	
</h:body>

</html>